---
title: "EDS 212 - Day 3 Conditionals & Loops"
author: "Colleen McCamy"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

# setting global options for the document in this section set up

library(tidyverse)
library(palmerpenguins)

```


## `if` statement fun

```{r}

burrito <- 2.4

if (burrito > 2) {
  print("I love burritos!")
}

# using if statements to create an output based on a variable

```

Creating a vector with strings

```{r}

my_ships <- c("Millenium Falcon", "X-wing", "Tie-Fighter", "Death Star")

str_detect(my_ships, pattern = "r")
# going through each element in the vector and if it contains "r" in the character - looking for any string match that exists in the vector

str_detect(my_ships, pattern = "x")
# case sensitive - can see that X-wing is not showing up as true since it is upper

starwars

```

```{r}

tatooine_characters <- starwars |> 
  filter(homeworld == "Tatooine")
# for each row check the condition if the homeworld value is equal to Tatooine then keep it, if not true don't keep it. Under the hood it is doing a if else (if Tatooine is true keep, if not remove the world)


# Using the in operator to check for multiple possible matches, the in operator asks a different option is that if any of these options are true then keep the row

tatooine_endor_naboo <- starwars |> 
  filter(homeworld %in% c("Tatooine", "Naboo", "Endor"))

# could write out long ways with using | the or operator and you would get the case if any of them are true -
# the in operator creates a shortcut for or statements - does the value of homeworld contatin a value that is in the following vector

# valuable for keep code concise, if you have an exisiting vector you could also plug that in

# string r string detect - does this pattern contain anywhere in this element, if it is yes returns TRUE

str_detect(my_ships, pattern = "x")

phrase <- "I love burritos!"

if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}

# could use string detect to print out patterns and not doing an if el statement

```


## Example of the `%in%` operator

```{r}



```


## `if-else` statement using

```{r}

pika <- 89.1

if (pika > 60) {
  print ("mega pika")
} else ("normal pika")


# all of programming is if this is true do this or if false do this
```


## if else if else

```{r}

marmot <- 2.8

if (marmot < 0.5) {
  print ("this is a small marmot")} else if (marmot >= 0.5 & marmot <3) {
    print ("this is a medium marmot")} else
  {
    print("this is a large marmot")
  }


```

# group by and summarize combine `groub_by() |> summarize()`

```{r}

penguins |> 
  group_by(species, island) |> 
  summarize(mean_bill_length = mean(bill_length_mm, na.rm = TRUE), sd_bill_length = sd(bill_length_mm, na.rm = TRUE),
            n = n())
  

# first penguins then group by species. just using group by does nothing but under the hood it says what ever you do next going to do what ever you want by the groups indicated
# summarize will use what ever function do the function (by group since there is a group by line) then will return it in a summarized table

#starting from penguins, under the hood telling R to recognize the different group in species and then next thing calculate that function for each of the different groups and then show it in a pretty table


# can add another grouping item by comma in the group_by function, this shows now specieis by islands for the 

# doesn't need a to add in a vector to expect the column names and is built to know and is a development arguement name

# this is R's version of creating pivot tables

# calculate the count or the number or rows in each group; 52 Adelie penguins at Torgersen 

#     when using n it counts every row - and if you omit na.rm = TRUE values, we can then set conditions to only count things that are not an NA values, ** A really good question to ask so that we know what count we are including


# running unique command

unique(penguins$species)
# since this is stored as a factor they have different levels

unique(starwars$eye_color)
# this is stored as characters so that there is no 

str_detect(starwars$eye_color, "blue")
# using string detect to see which characters have blue

```

## Group By Summarizes

```{r}

# 1. Find the mean and standard deviation of character height in `starwars` grouped by homeworld


starwars |> 
  group_by(homeworld) |> 
  summarize(sd_char_height = sd(height, na.rm = TRUE))

# 2. Find the maximum and minimum flipper length, and sample size for each species of penguins

penguins |> 
  group_by(species, sex) |> 
  summarize(max_flip_length = max(flipper_length_mm, na.rm = TRUE),
            min_flip_length = min(flipper_length_mm, na.rm = TRUE))


```

